name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Enable Flutter web & get dependencies
        run: |
          flutter config --enable-web
          flutter pub get

      - name: Derive repo name for base-href
        run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Build Flutter web release
        run: |
          flutter build web \
            --release \
            --web-renderer html \
            --base-href "/${{ env.REPO_NAME }}/"

      - name: Add .nojekyll file to disable Jekyll
        run: touch build/web/.nojekyll

      - name: Add SPA 404.html fallback (optional)
        run: cp build/web/index.html build/web/404.html

      # Optional: Add custom domain
      # - name: Add CNAME for custom domain
      #   run: echo "example.com" > build/web/CNAME

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
